paths: 
  data: "Data/"


data_versions:
  - 
  - "4-09-22"


train_config:
  loss: 'mse'
  metric: 'mae'
  epochs: 500 # I will make it long enough and we have early stop
  earl_stop: 50
  lr_reduce_pati: 5 # When it was 10, it was working but not in all casses

mlflow:
  track_uri: "http://127.0.0.1:5000"