paths: 
  data: "Data/"


data_versions:
  - "4-09-22"
  - "3-10-22"


train_config:
  learning_rate: 0.0002 #0.001
  decay: 100
  batch_size: 12
  loss: 'mse'
  metric: 'mae'
  epochs: 300
  earl_stop: 50
  lr_reduce_pati: 8 # When it was 10, it was working but not in all casses
  pic_shape: [256,256,3]
mlflow:
  track_uri: "http://127.0.0.1:5000"